name: "Publish (web)"

on:
    push:
        paths:
        - 'web/**'
    workflow_dispatch:

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - 
                name: Checkout code
                uses: actions/checkout@v4
                with:
                    ref: ${{ inputs.commit }}
                    submodules: recursive

            -
                name: Login to GitHub Container Registry
                uses: docker/login-action@v3
                with:
                    registry: ghcr.io
                    username: ${{ github.repository_owner }}
                    password: ${{ secrets.GITHUB_TOKEN }}

            - 
                name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3

            - 
                name: Build and push
                uses: docker/build-push-action@v6
                with:
                    context: web
                    platforms: linux/amd64,linux/arm64
                    push: true
                    tags: |
                        ghcr.io/${{ github.repository_owner }}/ente-web:${{ github.sha }}
                        ghcr.io/${{ github.repository_owner }}/ente-web:latest